/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Eduardo
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopBar = new javax.swing.JPanel();
        jPanelUser = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jPanelLeftBar = new javax.swing.JPanel();
        jPanelShowHide = new javax.swing.JPanel();
        jLabelShowHideBtn = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jLabelHomeBtn = new javax.swing.JLabel();
        jPanelTasks = new javax.swing.JPanel();
        jLabelTasksBtn = new javax.swing.JLabel();
        jPanelSchedules = new javax.swing.JPanel();
        jLabelSchedulesBtn = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelTopBar.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTopBar.setPreferredSize(new java.awt.Dimension(64, 64));

        jLabelUser.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userMenuIcon.png"))); // NOI18N
        jLabelUser.setText("UserName");

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanelTopBarLayout = new javax.swing.GroupLayout(jPanelTopBar);
        jPanelTopBar.setLayout(jPanelTopBarLayout);
        jPanelTopBarLayout.setHorizontalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTopBarLayout.setVerticalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLeftBar.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLeftBar.setPreferredSize(new java.awt.Dimension(190, 240));

        jPanelShowHide.setBackground(new java.awt.Color(0, 0, 0));
        jPanelShowHide.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabelShowHideBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelShowHideBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hideMenu.png"))); // NOI18N
        jLabelShowHideBtn.setText("Diminuir");
        jLabelShowHideBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelShowHideBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelShowHideBtn.setMinimumSize(new java.awt.Dimension(138, 64));
        jLabelShowHideBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelShowHideBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelShowHideLayout = new javax.swing.GroupLayout(jPanelShowHide);
        jPanelShowHide.setLayout(jPanelShowHideLayout);
        jPanelShowHideLayout.setHorizontalGroup(
            jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelShowHideBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelShowHideLayout.setVerticalGroup(
            jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelShowHideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelHome.setBackground(new java.awt.Color(0, 0, 0));
        jPanelHome.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabelHomeBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelHomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeIcon.png"))); // NOI18N
        jLabelHomeBtn.setText("Início");
        jLabelHomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelHomeBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelHomeBtn.setMinimumSize(new java.awt.Dimension(138, 64));
        jLabelHomeBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelHomeBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelTasks.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTasks.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabelTasksBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelTasksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskIcon.png"))); // NOI18N
        jLabelTasksBtn.setText("Tarefas");
        jLabelTasksBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelTasksBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelTasksBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelTasksBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelTasksLayout = new javax.swing.GroupLayout(jPanelTasks);
        jPanelTasks.setLayout(jPanelTasksLayout);
        jPanelTasksLayout.setHorizontalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTasksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTasksLayout.setVerticalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTasksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelSchedules.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSchedules.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabelSchedulesBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelSchedulesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduleIcon.png"))); // NOI18N
        jLabelSchedulesBtn.setText("Cronogramas");
        jLabelSchedulesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelSchedulesBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelSchedulesBtn.setMinimumSize(new java.awt.Dimension(138, 64));
        jLabelSchedulesBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelSchedulesBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelSchedulesLayout = new javax.swing.GroupLayout(jPanelSchedules);
        jPanelSchedules.setLayout(jPanelSchedulesLayout);
        jPanelSchedulesLayout.setHorizontalGroup(
            jPanelSchedulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSchedulesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSchedulesLayout.setVerticalGroup(
            jPanelSchedulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSchedulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftBarLayout = new javax.swing.GroupLayout(jPanelLeftBar);
        jPanelLeftBar.setLayout(jPanelLeftBarLayout);
        jPanelLeftBarLayout.setHorizontalGroup(
            jPanelLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelShowHide, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(jPanelSchedules, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelLeftBarLayout.setVerticalGroup(
            jPanelLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftBarLayout.createSequentialGroup()
                .addComponent(jPanelShowHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSchedules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelLeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLeftBar, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHomeBtn;
    private javax.swing.JLabel jLabelSchedulesBtn;
    private javax.swing.JLabel jLabelShowHideBtn;
    private javax.swing.JLabel jLabelTasksBtn;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLeftBar;
    private javax.swing.JPanel jPanelSchedules;
    private javax.swing.JPanel jPanelShowHide;
    private javax.swing.JPanel jPanelTasks;
    private javax.swing.JPanel jPanelTopBar;
    private javax.swing.JPanel jPanelUser;
    // End of variables declaration//GEN-END:variables
}
