/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ScheduleController;
import controller.ScheduleTaskController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import model.Schedule;
import model.ScheduleTask;
import model.Task;
import model.User;
import util.ButtonColumnCellRender;
import util.DeadlineColumnCellRender;
import util.DeadlineColumnCellRenderScheduleTask;
import util.ScheduleTableModel;
import util.ScheduleTaskTableModel;
import util.TaskTableModel;

/**
 *
 * @author Eduardo
 */
public class MainScreen extends javax.swing.JFrame {

    private boolean hidden;
    private final Color selectedColor = Color.GRAY;
    private final Color overColor = Color.DARK_GRAY;
    private final Color defaultColor = Color.BLACK;
    
    private TaskController taskController;
    private ScheduleController scheduleController;
    private ScheduleTaskController scheduleTaskController;
    
    private TaskTableModel taskModel;
    private ScheduleTableModel scheduleModel;
    private ScheduleTaskTableModel scheduleTaskModel;
    
    private Timer timer;
    private int seconds;
    private boolean isBreak;
    private int breaks; //quantidade de intervalos
    private Clip clip; //som despertador
    private ScheduledExecutorService executor;
    private boolean isRunning = false; //verifica se o timer está ativo

    
    private User user;
    private Schedule schedule;
    
    public MainScreen(User user) {
        initComponents();
        
        //atribuindo o nome de usuário ao campo de texto jLabelUser
        this.user = user;
        jLabelUser.setText(this.user.getName());
        
        initController();
        decorateTables();
        
        initFirstPanel();
        loadSound(); //carrega o som dos sistemas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScheduleTaskTable = new javax.swing.JPanel();
        jScrollPaneScheduleTask = new javax.swing.JScrollPane();
        jTableScheduleTask = new javax.swing.JTable();
        jPanelTimer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelTimerText = new javax.swing.JPanel();
        jLabelTimer = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jLabelScheduleTasksTitle = new javax.swing.JLabel();
        jLabelScheduleTasksAdd = new javax.swing.JLabel();
        jPanelScheduleTable = new javax.swing.JPanel();
        jScrollPaneSchedule = new javax.swing.JScrollPane();
        jTableSchedule = new javax.swing.JTable();
        jLabeSchedulesTitle = new javax.swing.JLabel();
        jLabelSchedulesAdd = new javax.swing.JLabel();
        jPanelTaskTable = new javax.swing.JPanel();
        jScrollPaneTask = new javax.swing.JScrollPane();
        jTableTask = new javax.swing.JTable();
        jLabelTasksTitle = new javax.swing.JLabel();
        jLabelTasksAdd = new javax.swing.JLabel();
        jPanelTopBar = new javax.swing.JPanel();
        jPanelUser = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jPanelLeftBar = new javax.swing.JPanel();
        jPanelShowHide = new javax.swing.JPanel();
        jLabelShowHideBtn = new javax.swing.JLabel();
        jPanelQuit = new javax.swing.JPanel();
        jLabelQuitBtn = new javax.swing.JLabel();
        jPanelTasks = new javax.swing.JPanel();
        jLabelTasksBtn = new javax.swing.JLabel();
        jPanelSchedules = new javax.swing.JPanel();
        jLabelSchedulesBtn = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();

        jPanelScheduleTaskTable.setBackground(new java.awt.Color(18, 30, 49));

        jTableScheduleTask.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTableScheduleTask.setForeground(new java.awt.Color(255, 255, 255));
        jTableScheduleTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableScheduleTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableScheduleTaskMouseClicked(evt);
            }
        });
        jScrollPaneScheduleTask.setViewportView(jTableScheduleTask);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cronometro");
        jLabel1.setToolTipText("");

        jPanelTimerText.setBackground(new java.awt.Color(0, 0, 0));

        jLabelTimer.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTimer.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelTimer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTimer.setText("00:30:00");

        javax.swing.GroupLayout jPanelTimerTextLayout = new javax.swing.GroupLayout(jPanelTimerText);
        jPanelTimerText.setLayout(jPanelTimerTextLayout);
        jPanelTimerTextLayout.setHorizontalGroup(
            jPanelTimerTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );
        jPanelTimerTextLayout.setVerticalGroup(
            jPanelTimerTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimerTextLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTimer)
                .addGap(38, 38, 38))
        );

        jButtonStart.setBackground(new java.awt.Color(0, 0, 0));
        jButtonStart.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonStart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStart.setText("Iniciar");
        jButtonStart.setBorder(null);
        jButtonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStartMouseClicked(evt);
            }
        });

        jButtonStop.setBackground(new java.awt.Color(102, 102, 102));
        jButtonStop.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonStop.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStop.setText("Parar");
        jButtonStop.setBorder(null);
        jButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTimerLayout = new javax.swing.GroupLayout(jPanelTimer);
        jPanelTimer.setLayout(jPanelTimerLayout);
        jPanelTimerLayout.setHorizontalGroup(
            jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelTimerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTimerLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jPanelTimerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanelTimerLayout.setVerticalGroup(
            jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTimerText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelScheduleTasksTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelScheduleTasksTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelScheduleTasksTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScheduleTasksTitle.setText("Tarefas do Cronograma");

        jLabelScheduleTasksAdd.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelScheduleTasksAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelScheduleTasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addIcon.png"))); // NOI18N
        jLabelScheduleTasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelScheduleTasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelScheduleTaskTableLayout = new javax.swing.GroupLayout(jPanelScheduleTaskTable);
        jPanelScheduleTaskTable.setLayout(jPanelScheduleTaskTableLayout);
        jPanelScheduleTaskTableLayout.setHorizontalGroup(
            jPanelScheduleTaskTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneScheduleTask, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScheduleTaskTableLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabelScheduleTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelScheduleTasksAdd)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanelScheduleTaskTableLayout.setVerticalGroup(
            jPanelScheduleTaskTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScheduleTaskTableLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelScheduleTaskTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScheduleTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScheduleTasksAdd))
                .addGap(6, 6, 6)
                .addComponent(jScrollPaneScheduleTask, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelScheduleTable.setBackground(new java.awt.Color(18, 30, 49));

        jTableSchedule.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSchedule.setShowGrid(true);
        jTableSchedule.setShowVerticalLines(false);
        jTableSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableScheduleMouseClicked(evt);
            }
        });
        jScrollPaneSchedule.setViewportView(jTableSchedule);

        jLabeSchedulesTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabeSchedulesTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabeSchedulesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeSchedulesTitle.setText("Cronogramas");

        jLabelSchedulesAdd.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelSchedulesAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSchedulesAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addIcon.png"))); // NOI18N
        jLabelSchedulesAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSchedulesAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelScheduleTableLayout = new javax.swing.GroupLayout(jPanelScheduleTable);
        jPanelScheduleTable.setLayout(jPanelScheduleTableLayout);
        jPanelScheduleTableLayout.setHorizontalGroup(
            jPanelScheduleTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScheduleTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeSchedulesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSchedulesAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelScheduleTableLayout.setVerticalGroup(
            jPanelScheduleTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScheduleTableLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelScheduleTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeSchedulesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSchedulesAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
        );

        jPanelTaskTable.setBackground(new java.awt.Color(18, 30, 49));

        jTableTask.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTableTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTaskMouseClicked(evt);
            }
        });
        jScrollPaneTask.setViewportView(jTableTask);

        jLabelTasksTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelTasksTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTasksTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTasksTitle.setText("Tarefas");

        jLabelTasksAdd.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTasksAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTasksAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addIcon.png"))); // NOI18N
        jLabelTasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTaskTableLayout = new javax.swing.GroupLayout(jPanelTaskTable);
        jPanelTaskTable.setLayout(jPanelTaskTableLayout);
        jPanelTaskTableLayout.setHorizontalGroup(
            jPanelTaskTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTask, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addGroup(jPanelTaskTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTasksAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTaskTableLayout.setVerticalGroup(
            jPanelTaskTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTaskTableLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelTaskTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTasksAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTask, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanelTopBar.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTopBar.setPreferredSize(new java.awt.Dimension(64, 64));

        jPanelUser.setBackground(new java.awt.Color(0, 0, 0));

        jLabelUser.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUser.setText("UserName");

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanelTopBarLayout = new javax.swing.GroupLayout(jPanelTopBar);
        jPanelTopBar.setLayout(jPanelTopBarLayout);
        jPanelTopBarLayout.setHorizontalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelTopBarLayout.setVerticalGroup(
            jPanelTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelTopBar, java.awt.BorderLayout.PAGE_START);

        jPanelLeftBar.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLeftBar.setPreferredSize(new java.awt.Dimension(190, 240));

        jPanelShowHide.setBackground(new java.awt.Color(0, 0, 0));
        jPanelShowHide.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelShowHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelShowHideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelShowHideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelShowHideMouseExited(evt);
            }
        });

        jLabelShowHideBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelShowHideBtn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelShowHideBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hideMenu.png"))); // NOI18N
        jLabelShowHideBtn.setText("Diminuir");
        jLabelShowHideBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelShowHideBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelShowHideBtn.setMinimumSize(new java.awt.Dimension(138, 64));
        jLabelShowHideBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelShowHideBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelShowHideLayout = new javax.swing.GroupLayout(jPanelShowHide);
        jPanelShowHide.setLayout(jPanelShowHideLayout);
        jPanelShowHideLayout.setHorizontalGroup(
            jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelShowHideBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelShowHideLayout.setVerticalGroup(
            jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelShowHideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelQuit.setBackground(new java.awt.Color(0, 0, 0));
        jPanelQuit.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQuitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelQuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelQuitMouseExited(evt);
            }
        });

        jLabelQuitBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelQuitBtn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quitIcon.png"))); // NOI18N
        jLabelQuitBtn.setText("Sair");
        jLabelQuitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelQuitBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelQuitBtn.setMinimumSize(new java.awt.Dimension(138, 64));
        jLabelQuitBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelQuitBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelQuitLayout = new javax.swing.GroupLayout(jPanelQuit);
        jPanelQuit.setLayout(jPanelQuitLayout);
        jPanelQuitLayout.setHorizontalGroup(
            jPanelQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelQuitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelQuitLayout.setVerticalGroup(
            jPanelQuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelQuitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelTasks.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTasks.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTasksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelTasksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelTasksMouseExited(evt);
            }
        });

        jLabelTasksBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelTasksBtn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTasksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskIcon.png"))); // NOI18N
        jLabelTasksBtn.setText("Tarefas");
        jLabelTasksBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelTasksBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelTasksBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelTasksBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelTasksLayout = new javax.swing.GroupLayout(jPanelTasks);
        jPanelTasks.setLayout(jPanelTasksLayout);
        jPanelTasksLayout.setHorizontalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTasksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelTasksLayout.setVerticalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTasksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelSchedules.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSchedules.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelSchedules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSchedulesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSchedulesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSchedulesMouseExited(evt);
            }
        });

        jLabelSchedulesBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelSchedulesBtn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSchedulesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduleIcon.png"))); // NOI18N
        jLabelSchedulesBtn.setText("Cronogramas");
        jLabelSchedulesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelSchedulesBtn.setMaximumSize(new java.awt.Dimension(168, 64));
        jLabelSchedulesBtn.setMinimumSize(new java.awt.Dimension(138, 64));
        jLabelSchedulesBtn.setPreferredSize(new java.awt.Dimension(148, 64));
        jLabelSchedulesBtn.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelSchedulesLayout = new javax.swing.GroupLayout(jPanelSchedules);
        jPanelSchedules.setLayout(jPanelSchedulesLayout);
        jPanelSchedulesLayout.setHorizontalGroup(
            jPanelSchedulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSchedulesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanelSchedulesLayout.setVerticalGroup(
            jPanelSchedulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSchedulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLeftBarLayout = new javax.swing.GroupLayout(jPanelLeftBar);
        jPanelLeftBar.setLayout(jPanelLeftBarLayout);
        jPanelLeftBarLayout.setHorizontalGroup(
            jPanelLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelShowHide, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelSchedules, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelLeftBarLayout.setVerticalGroup(
            jPanelLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftBarLayout.createSequentialGroup()
                .addComponent(jPanelShowHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSchedules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jPanelQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelLeftBar, java.awt.BorderLayout.LINE_START);

        jPanelContent.setBackground(new java.awt.Color(18, 30, 49));
        jPanelContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelQuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuitMouseEntered
        // mudando cor ao passar mouse por cima
        mouseOver(jPanelQuit);
    }//GEN-LAST:event_jPanelQuitMouseEntered

    private void jPanelTasksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTasksMouseEntered
        // mudando cor ao passar mouse por cima
        mouseOver(jPanelTasks);
    }//GEN-LAST:event_jPanelTasksMouseEntered

    private void jPanelSchedulesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSchedulesMouseEntered
        // mudando cor ao passar mouse por cima
        mouseOver(jPanelSchedules);
    }//GEN-LAST:event_jPanelSchedulesMouseEntered

    private void jPanelShowHideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelShowHideMouseEntered
        // mudando cor ao passar mouse por cima
        mouseOver(jPanelShowHide);
    }//GEN-LAST:event_jPanelShowHideMouseEntered

    private void jPanelShowHideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelShowHideMouseExited
        // mudando cor ao retirar o  mouse de cima
        mouseExit(jPanelShowHide);
    }//GEN-LAST:event_jPanelShowHideMouseExited

    private void jPanelQuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuitMouseExited
        // mudando cor ao retirar o  mouse de cima
        mouseExit(jPanelQuit);
    }//GEN-LAST:event_jPanelQuitMouseExited

    private void jPanelTasksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTasksMouseExited
        // mudando cor ao retirar o  mouse de cima
        mouseExit(jPanelTasks);
    }//GEN-LAST:event_jPanelTasksMouseExited

    private void jPanelSchedulesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSchedulesMouseExited
        // mudando cor ao retirar o  mouse de cima
        mouseExit(jPanelSchedules);
    }//GEN-LAST:event_jPanelSchedulesMouseExited

    private void jPanelQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuitMouseClicked
        // Saindo da tela principal e voltando para a tela de login ao clicar no botão sair
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
                
        //fecha essa tela.
        dispose();
    }//GEN-LAST:event_jPanelQuitMouseClicked

    private void jPanelShowHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelShowHideMouseClicked
        
        ImageIcon im = null;
        
        //muda o icone e o tamanho do menu ao clicar
        if(hidden){
            im = new ImageIcon(getClass().getResource("/hideMenu.png"));
            jPanelLeftBar.setPreferredSize(new Dimension(190, jPanelLeftBar.size().height));
        }else{
            im = new ImageIcon(getClass().getResource("/showMenu.png"));
            jPanelLeftBar.setPreferredSize(new Dimension(64, jPanelLeftBar.size().height));
        }
        hidden = !hidden;
        jLabelShowHideBtn.setIcon(im);
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jPanelShowHideMouseClicked

    private void jPanelTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTasksMouseClicked
        // deixa o item selecionado
        selectedMenu(jPanelTasks);
        loadTasks(user.getId());
    }//GEN-LAST:event_jPanelTasksMouseClicked

    private void jPanelSchedulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSchedulesMouseClicked
        // deixar o item selecionado
        selectedMenu(jPanelSchedules);
        loadSchedules(user.getId());
    }//GEN-LAST:event_jPanelSchedulesMouseClicked

    private void jLabelTasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTasksAddMouseClicked
        // Abrindo janela de adicionar tarefas
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        
        taskDialogScreen.setUserId(user.getId());
        
        taskDialogScreen.setVisible(true);
        
        taskDialogScreen.addWindowListener(new WindowAdapter() {
           public void windowClosed(WindowEvent e){
               loadTasks(user.getId());
           } 
        });
    }//GEN-LAST:event_jLabelTasksAddMouseClicked

    private void jTableTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTaskMouseClicked
        // pegando a tarefa clicada na tabela atravez da posição do evento de clique do mouse
        // pegar a tabela atravez da posição do evento que aconteceu na tela
        int rowIndex = jTableTask.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTask.columnAtPoint(evt.getPoint());
        
        Task task = taskModel.getTasks().get(rowIndex);
        switch (columnIndex) {
            case 3:
                taskController.update(task);
                break;
            case 4:
                //abre dialog screen de atualização de tarefas
                TaskUpdateDialogScreen taskUpdateDialogScreen = new TaskUpdateDialogScreen(this, rootPaneCheckingEnabled, task);

                taskUpdateDialogScreen.setVisible(true);

                taskUpdateDialogScreen.addWindowListener(new WindowAdapter() {
                   public void windowClosed(WindowEvent e){
                       loadTasks(user.getId());
                   } 
                });
                break;            
            case 5:
                taskController.removeById(task.getId());
                taskModel.getTasks().remove(task);
                
                loadTasks(user.getId());
                break;            
        }
    }//GEN-LAST:event_jTableTaskMouseClicked

    private void jLabelSchedulesAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSchedulesAddMouseClicked
        // Abrindo janela de adicionar cronogramas
        ScheduleDialogScreen scheduleDialogScreen = new ScheduleDialogScreen(this, rootPaneCheckingEnabled);
        
        scheduleDialogScreen.setUserId(user.getId());
        
        scheduleDialogScreen.setVisible(true);
        
        scheduleDialogScreen.addWindowListener(new WindowAdapter() {
           public void windowClosed(WindowEvent e){
               loadSchedules(user.getId());
           } 
        });
    }//GEN-LAST:event_jLabelSchedulesAddMouseClicked

    private void jTableScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableScheduleMouseClicked
        // pegando o cronograma clicado na tabela atravez da posição do evento de clique do mouse
        // pegar o cronograma atravez da posição do evento que aconteceu na tela
        int rowIndex = jTableSchedule.rowAtPoint(evt.getPoint());
        int columnIndex = jTableSchedule.columnAtPoint(evt.getPoint());
        
        schedule = scheduleModel.getSchedules().get(rowIndex);
        switch (columnIndex) {
            case 2:
                //abre dialog screen de atualização de cronogramas
                ScheduleUpdateDialogScreen scheduleUpdateDialogScreen = new ScheduleUpdateDialogScreen(this, rootPaneCheckingEnabled, schedule);

                scheduleUpdateDialogScreen.setVisible(true);

                scheduleUpdateDialogScreen.addWindowListener(new WindowAdapter() {
                   public void windowClosed(WindowEvent e){
                       loadSchedules(user.getId());
                   } 
                });
                break;            
            case 3:
                scheduleController.removeById(schedule.getId());
                scheduleModel.getSchedules().remove(schedule);
                
                loadSchedules(user.getId());
                break;
            default:
                selectedMenu(jPanelScheduleTaskTable);
                seconds = schedule.getTimeWorking() * 60;
                breaks = 0;
                timerFormat();
                loadScheduleTask( schedule.getId(), user.getId());
                break;
        }
    }//GEN-LAST:event_jTableScheduleMouseClicked

    private void jLabelScheduleTasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelScheduleTasksAddMouseClicked
        // Abrindo janela de adicionar tarefas ao cronograma
        ScheduleTaskDialogScreen scheduleTaskDialogScreen = new ScheduleTaskDialogScreen(this, rootPaneCheckingEnabled, 
                user.getId(), schedule.getId());
        
        scheduleTaskDialogScreen.setVisible(true);
        
        scheduleTaskDialogScreen.addWindowListener(new WindowAdapter() {
           public void windowClosed(WindowEvent e){
               loadScheduleTask(schedule.getId(), user.getId());
           } 
        });
    }//GEN-LAST:event_jLabelScheduleTasksAddMouseClicked

    private void jTableScheduleTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableScheduleTaskMouseClicked
        // pegando a tarefa clicada na tabela atravez da posição do evento de clique do mouse
        // pegar a tabela atravez da posição do evento que aconteceu na tela
        int rowIndex = jTableScheduleTask.rowAtPoint(evt.getPoint());
        int columnIndex = jTableScheduleTask.columnAtPoint(evt.getPoint());
        
        ScheduleTask scheduleTask = scheduleTaskModel.getScheduleTasks().get(rowIndex);

        switch (columnIndex) {
            case 3:
                scheduleTaskController.update(scheduleTask);
                break;
            case 4:
                //abre dialog screen de atualização de tarefas
                ScheduleTaskUpdateDialogScreen scheduleTaskUpdateDialogScreen = new ScheduleTaskUpdateDialogScreen(this, rootPaneCheckingEnabled, scheduleTask);

                scheduleTaskUpdateDialogScreen.setVisible(true);

                scheduleTaskUpdateDialogScreen.addWindowListener(new WindowAdapter() {
                   public void windowClosed(WindowEvent e){
                       loadScheduleTask(schedule.getId(), user.getId());
                   } 
                });
                break;            
            case 5:
                scheduleTaskController.removeById(scheduleTask.getId());
                scheduleTaskModel.getScheduleTasks().remove(scheduleTask);
                
                loadScheduleTask(schedule.getId(), user.getId());
                break;            
        }
    }//GEN-LAST:event_jTableScheduleTaskMouseClicked

    private void jButtonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartMouseClicked
        startTimer();
    }//GEN-LAST:event_jButtonStartMouseClicked

    private void jButtonStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseClicked
        stopTimer();
    }//GEN-LAST:event_jButtonStopMouseClicked
    //muda o fundo do item que o mouse estiver em cima
    private void mouseOver(JPanel jPanel){
        if(jPanel.getBackground() == selectedColor){
            return;
        }
        jPanel.setBackground(overColor);
    }
    //volta a cor ao normal ao tirar o mouse de cima
    private void mouseExit(JPanel jPanel){
        if(jPanel.getBackground() == selectedColor){
            return;
        }
        jPanel.setBackground(defaultColor);
    }
    //muda o fundo do item de menu selecionado
    private void selectedMenu(JPanel selected){
        stopTimer();//ao sair do cronograma para o contador
        jPanelSchedules.setBackground(defaultColor);
        jPanelTasks.setBackground(defaultColor);
        if(selected != jPanelScheduleTaskTable){
            selected.setBackground(selectedColor);
        }
    }
    
    public void initController(){
        taskController = new TaskController();
        scheduleController = new ScheduleController();
        scheduleTaskController = new ScheduleTaskController();
        taskModel = new TaskTableModel();
        jTableTask.setModel(taskModel);
        scheduleModel = new ScheduleTableModel();
        jTableSchedule.setModel(scheduleModel);
        scheduleTaskModel = new ScheduleTaskTableModel();
        jTableScheduleTask.setModel(scheduleTaskModel);
        
    }
    
    public void initFirstPanel(){
        // deixa o item selecionado
        selectedMenu(jPanelTasks);
        //carrega lista de tarefas
        loadTasks(user.getId());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabeSchedulesTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelQuitBtn;
    private javax.swing.JLabel jLabelScheduleTasksAdd;
    private javax.swing.JLabel jLabelScheduleTasksTitle;
    private javax.swing.JLabel jLabelSchedulesAdd;
    private javax.swing.JLabel jLabelSchedulesBtn;
    private javax.swing.JLabel jLabelShowHideBtn;
    private javax.swing.JLabel jLabelTasksAdd;
    private javax.swing.JLabel jLabelTasksBtn;
    private javax.swing.JLabel jLabelTasksTitle;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelLeftBar;
    private javax.swing.JPanel jPanelQuit;
    private javax.swing.JPanel jPanelScheduleTable;
    private javax.swing.JPanel jPanelScheduleTaskTable;
    private javax.swing.JPanel jPanelSchedules;
    private javax.swing.JPanel jPanelShowHide;
    private javax.swing.JPanel jPanelTaskTable;
    private javax.swing.JPanel jPanelTasks;
    private javax.swing.JPanel jPanelTimer;
    private javax.swing.JPanel jPanelTimerText;
    private javax.swing.JPanel jPanelTopBar;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JScrollPane jScrollPaneSchedule;
    private javax.swing.JScrollPane jScrollPaneScheduleTask;
    private javax.swing.JScrollPane jScrollPaneTask;
    private javax.swing.JTable jTableSchedule;
    private javax.swing.JTable jTableScheduleTask;
    private javax.swing.JTable jTableTask;
    // End of variables declaration//GEN-END:variables

    public void decorateTables(){
        
        //tabela Tasks
	jTableTask.getTableHeader().setBackground(new Color(0,0,0));
	jTableTask.getTableHeader().setForeground(new Color(255, 255, 255));
        
	jTableTask.setFont (new Font("Comic Sans", Font.BOLD, 14));
        jTableTask.setBackground(new Color(18,30,49));
        jTableTask.setForeground(new Color(255,255,255));
        jTableTask.setRowHeight(40);
        
        jTableTask.getColumnModel().getColumn(2)
                .setCellRenderer(new DeadlineColumnCellRender());
        
        //adicionando os icones de atualizar e remover
        jTableTask.getColumnModel().getColumn(4)
                .setCellRenderer(new ButtonColumnCellRender("updateIcon"));
        
        jTableTask.getColumnModel().getColumn(5)
                .setCellRenderer(new ButtonColumnCellRender("removeIcon"));
        
        //tabela Schedules
	jTableSchedule.getTableHeader().setBackground(new Color(0,0,0));
	jTableSchedule.getTableHeader().setForeground(new Color(255, 255, 255));
        
	jTableSchedule.setFont (new Font("Comic Sans", Font.BOLD, 14));
        jTableSchedule.setBackground(new Color(18,30,49));
        jTableSchedule.setForeground(new Color(255,255,255));
        jTableSchedule.setRowHeight(40);
        
        //adicionando os icones de atualizar e remover
        jTableSchedule.getColumnModel().getColumn(2)
                .setCellRenderer(new ButtonColumnCellRender("updateIcon"));
        
        jTableSchedule.getColumnModel().getColumn(3)
                .setCellRenderer(new ButtonColumnCellRender("removeIcon"));
        
        //tabela scheduleTasks
	jTableScheduleTask.getTableHeader().setBackground(new Color(0,0,0));
	jTableScheduleTask.getTableHeader().setForeground(new Color(255, 255, 255));
        
	jTableScheduleTask.setFont (new Font("Comic Sans", Font.BOLD, 14));
        jTableScheduleTask.setBackground(new Color(18,30,49));
        jTableScheduleTask.setForeground(new Color(255,255,255));
        jTableScheduleTask.setRowHeight(40);
        
        jTableScheduleTask.getColumnModel().getColumn(2)
                .setCellRenderer(new DeadlineColumnCellRenderScheduleTask());
        
        //adicionando os icones de atualizar e remover
        jTableScheduleTask.getColumnModel().getColumn(4)
                .setCellRenderer(new ButtonColumnCellRender("updateIcon"));
        
        jTableScheduleTask.getColumnModel().getColumn(5)
                .setCellRenderer(new ButtonColumnCellRender("removeIcon"));
        //jTableTask.setAutoCreateRowSorter(true);//ativa ordenação automática por coluna
    }
    public void loadTasks(int idUser){
	List<Task> tasks = taskController.getAll(idUser); //todas as tarefas do usuário
        
        taskModel.setTasks(tasks);
        
        showJMenuTable(1);
    }
    public void loadSchedules(int idUser){
        List<Schedule> schedules = scheduleController.getAll(idUser);
        
        scheduleModel.setSchedules(schedules);
        
        showJMenuTable(2);
    }
    public void loadScheduleTask(int idSchedule, int idUser){
        List<ScheduleTask> scheduleTasks = scheduleTaskController.getAll(idSchedule, idUser);

        scheduleTaskModel.setScheduleTasks(scheduleTasks);

        showJMenuTable(3);
    }
    //esconde qualquer outro jPanel aberto dentro de jPanelContent e abre o 1 - jPanelTableTask, 2 - jPanelTableSchedules, 3 - jPanelTableScheduleTask
    public void showJMenuTable(int item){
        if(jPanelScheduleTable.isVisible()){
            jPanelScheduleTable.setVisible(false);
            jPanelContent.remove(jPanelScheduleTable);
        }
        if(jPanelScheduleTaskTable.isVisible()){
            jPanelScheduleTaskTable.setVisible(false);
            jPanelContent.remove(jPanelScheduleTaskTable);
        }
        if(jPanelTaskTable.isVisible()){
            jPanelTaskTable.setVisible(false);
            jPanelContent.remove(jPanelTaskTable);
        }
        switch (item) {
            case 1:
                jPanelContent.add(jPanelTaskTable);
                jPanelTaskTable.setSize(jPanelContent.getWidth(), jPanelContent.getHeight());
                jPanelTaskTable.setVisible(true);
                break;
            case 2:
                jPanelContent.add(jPanelScheduleTable);
                jPanelScheduleTable.setSize(jPanelContent.getWidth(), jPanelContent.getHeight());
                jPanelScheduleTable.setVisible(true);
                break;
            case 3:
                jPanelContent.add(jPanelScheduleTaskTable);
                jPanelScheduleTaskTable.setSize(jPanelContent.getWidth(), jPanelContent.getHeight());
                jPanelScheduleTaskTable.setVisible(true);
                break;
            default:
                break;
        }
        jPanelContent.revalidate();
    }
    private void timerFormat(){
        int hour = seconds / 3600;
        int min = (seconds % 3600) / 60;
        int sec = seconds % 60;
        jLabelTimer.setText(String.format("%02d:%02d:%02d", hour, min, sec));
    }
    private void startTimer(){
        if(!isRunning){
            isRunning = true;
            timer = new Timer(1000, e -> {
                if(seconds > 0){
                    seconds--;
                    timerFormat();
                }
                else{
                    stopTimer();
                    //muda de intervalo para trabalho e de trabalho para intervalo
                    isBreak = !isBreak;
                    //verifica se é intervalo ou tempo de trabalhar e atribui o valor em segundos
                    setTimerInfo();
                    //ativa o som de despertador por 2 segundos
                    clip.start();
                    //tocar por 2 segundos
                    executor = Executors.newSingleThreadScheduledExecutor();
                    executor.schedule(() -> clip.stop(), 2, TimeUnit.SECONDS);
                    timerFormat();
                    startTimer();
                }
            });
            if(isBreak == false){
                jPanelTimerText.setBackground(new Color(0,255,0));
            }
            else{
                jPanelTimerText.setBackground(new Color(255,0,0));
            }
            timer.start();
        }
    }
    private void stopTimer(){
        if(isRunning){
            isRunning = false;
            timer.stop();
            if (executor != null) {
            executor.shutdownNow();
            }
            jPanelTimerText.setBackground(new Color(0,0,0));
        }
    }
    
    private boolean isBigBreak(){
        return breaks % 4 == 0;
    }
    private void setTimerInfo(){
        if(isBreak == false){
            jPanelTimerText.setBackground(new Color(0,255,0));
            seconds = schedule.getTimeWorking()* 60;
        }
        else{
            jPanelTimerText.setBackground(new Color(255,0,0));
            breaks++;
            if(isBigBreak()){
                seconds = schedule.getBigBreak() * 60;
            }
            else{
                seconds = schedule.getShortBreak()* 60;
            }
        }
    }
    private void loadSound(){
        //utilizando uma thread separada para quando tocar o audio não ter atrasos
        new Thread(() -> {
            try {
                clip = AudioSystem.getClip();
                clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/alarm.wav")));
                //deixa o som em loop para nunca acabar.
                clip.loop(Clip.LOOP_CONTINUOUSLY);
                clip.stop();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jPanelContent, "Não foi possível carregar o arquivo de audio do despertador! " + e.getMessage());
            }
        }).start();
    }
}
